### PR TITLE
add support for CloudFront forwarding protocol

### PR DESCRIPTION
**Pull request by gmazovec**
CloudFront is sending custom header CloudFront-Forwarded-Proto.

### CODE REVIEW

**Comment by webaware** [comment]
@gmazovec thanks for the submission. It sounds like a good idea. 

I've read some (minimal) [AWS doco on this](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-protocol), and it sounds like it could be useful for presenting the correct content based on the protocol.

Can you just confirm for me please, do you not receive the `HTTP_X_FORWARDED_PROTO` header when you have this content caching mode configured? I saw in some other doco that this header is removed from incoming requests, but I thought it was still sent to the server when the requesting protocol was HTTPS.

**Comment by gmazovec** [comment]
Hey Ross

I was migrating from CloudFlaire to CloudFront and I was having problems
with your plugin because CloudFront was not sending X-Forwarded-Proto.
After checking the incoming headers I found out that WP was receiving
CloudFront-Forwarded-Proto.

Cheers Gregor

**Comment by webaware** [comment]
Thanks. I think what I'll do here is add another option for this header, because it doesn't mean the same thing as the `X-Forwarded-Proto` header, and both could be present but some people might prefer to set only on the `CloudFront-Forwarded-Proto` header.

I reckon I'll get this, and another open PR, into a release sometime in the next few days. When you see an update come through, please change your settings to use the `CloudFront-Forwarded-Proto` header.

**Comment by gmazovec** [comment]
I was thinking about making another option for this header. But I came to
conclusion that this header is actually of same category as
X-Forwarded-Proto just more specific about origin. I also thing that
additional option would just make user more confused. I would rather just
add this header to description of current option.

Make sense? What do you think?

**Comment by webaware** [comment]
No, I reckon it's subtly different. It says that Cloudfront is requesting content to be cached for https, and doesn't necessarily say that the connection is https. I'll make it a separate option. Today!

**Pull request closed without merging**
